jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.3-node
    steps:
      - checkout
      - run: java --version
      - run: gradle --version
      - run: gradle build
      - run: gradle test