/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_ci_cd;

import java.util.ArrayList;
import java.util.Arrays;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testFound(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
        assertTrue(App.search(array,4));   
    }
    @Test
    public void testNotFound(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
        assertFalse(App.search(array,5));   
    }
    @Test
    public void testEmptyFound(){
        ArrayList<Integer> array = new ArrayList<>();
        assertFalse(App.search(array,4));   
    }

    @Test
    public void zeroAllNotes(){
        assertEquals(App.input_controls("0","180303024","0","0"),0);
        //Öğrenci notlarının sıfır girilmesi durumları   
    }

    @Test
    public void nullNotes(){
        assertEquals(App.input_controls("","","",""), 0.0);   
        //İnputların boş gelmesi durumları
    }

    @Test
    public void noteExampleControl(){
        assertEquals(App.input_controls("100\n100", "180303024", "100", "100"), 100.0);   
        //Sonuc notunun dogru olup olmaması durumu
    }

    @Test
    public void studentNoLengthControl(){
        assertEquals(App.input_controls("100\n100", "012", "100", "100"), 0.0);   
        //Öğrenci numarasının 9 haneden oluşup oluşmaması durumu
    }

    @Test
    public void quizMultiControl(){
        assertEquals(App.input_controls("100", "012", "100", "100"), 0.0);   
        //Tek quizden girilmesi durumu
    }

}
